### ISSUE TITLE
Question regarding downloading the 'project json'

### ISSUE THREAD

**Issue by sellingsolutions** [Erfan-Shooraj/ifc2b3dm#1]
What do you mean when you say 'download directly from bimserver' ?
```
// Get the Project Json
			Long roid = client.getServiceInterface().getTopLevelProjectByName(PROJECT).getLastRevisionId();
			DownloadProjectJSON(client, roid); //Downloads malformed json on large models sometimes
												 //Better to download directly from bimserver and put in the model folder
```

**Comment by Erfan-Shooraj** [comment]
It means just launch BIMServer and download your project with Json serializer and put it in the same folder as defined in your:

public static String JSON_PATH = CONVERTER_PATH + PROJECT + "\\" + PROJECT + ".json";

You only need to do it if you get malformed json from the function.

**Comment by sellingsolutions** [comment]
All right, it sounded like there was some alternate API that was more reliable. Thanks!
