### ISSUE TITLE
Converter path? 

### ISSUE THREAD

**Issue by geolocus** [Erfan-Shooraj/ifc2b3dm#5]
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:43: error: illegal escape character
        public static String CONVERTER_PATH = "C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter"; //Enter your converter path

Which one is it?

**Comment by Erfan-Shooraj** [comment]
You need to add another backslash to all your backslashes and one more to the end, which eclipse usually does it for you:

C:\\bin\\ifc2b3dm\\IFC2GLTFs\\src\\main\\java\\ifcconverter\\

And for this converter folder, I usually create a separate folder to the code, but it shouldn't really matter to give you an error.

**Comment by geolocus** [comment]
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:16: error: package org.bimserver.client does not exist
import org.bimserver.client.BimServerClient;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:17: error: package org.bimserver.client.json does not exist
import org.bimserver.client.json.JsonBimServerClientFactory;
                                ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:18: error: package org.bimserver.shared does not exist
import org.bimserver.shared.ChannelConnectionException;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:19: error: package org.bimserver.shared does not exist
import org.bimserver.shared.UsernamePasswordAuthenticationInfo;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:20: error: package org.bimserver.shared.exceptions does not exist

Do you have any clue why I couldnt get my BIM Server connected?

Thank you so much for answering to my dumb questions :) because its really hard for the first time running java things..

**Comment by Erfan-Shooraj** [comment]
Discussed here #6
