### ISSUE TITLE
Bim.server.client and Bim.server.shared problem

### ISSUE THREAD

**Issue by geolocus** [Erfan-Shooraj/ifc2b3dm#6]
Hey,

Looks like converter cannot either find Bim.server or Im doing something not right.

Please can someone give me guidance here? 

C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:16: error: package org.bimserver.client does not exist
import org.bimserver.client.BimServerClient;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:17: error: package org.bimserver.client.json does not exist
import org.bimserver.client.json.JsonBimServerClientFactory;
                                ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:18: error: package org.bimserver.shared does not exist
import org.bimserver.shared.ChannelConnectionException;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:19: error: package org.bimserver.shared does not exist
import org.bimserver.shared.UsernamePasswordAuthenticationInfo;
                           ^
C:\bin\ifc2b3dm\IFC2GLTFs\src\main\java\ifcconverter\Main.java:20: error: package org.bimserver.shared.exceptions does not exist
import org.bimserver.shared.exceptions.BimServerClientException;

**Comment by Erfan-Shooraj** [comment]
Hey,

It looks like you don't have BimServer client in your workspace and their packages. It's not enough to have the server running, you also need their source code. There's some information about that here:

https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient
https://github.com/opensourceBIM/BIMserver/wiki/BimServerClientMavenEclipse

Once you have the packages, I think you should get past this error.

**Comment by geolocus** [comment]
Maybe its Dependency problem? Idk where to change it. 




Gauti „Outlook“, skirtą „Android“







On Sun, Jun 2, 2019 at 7:03 AM +0200, "Erfan-Shooraj" <notifications@github.com> wrote:












Hey,


It looks like you don't have BimServer client in your workspace and their packages. It's not enough to have the server running, you also need their source code. There's some information about that here:


https://github.com/opensourceBIM/BIMserver/wiki/BimServerClient

https://github.com/opensourceBIM/BIMserver/wiki/BimServerClientMavenEclipse


Once you have the packages, I think you should get past this error.

**Comment by Erfan-Shooraj** [comment]
It is a dependency problem. The easiest way to get around it is to download their entire github repo and import it into your workspace and then build your workspace

**Comment by geolocus** [comment]
How many hours of work for specialist to launch it correctly with all the Libs ? 

Thank you for answering so much. I have no clue and it helps a lot with your support.

**Comment by Erfan-Shooraj** [comment]
No problem.

It shouldn't take more than an hour to set it up. But after the set up the conversion time depends on your model and could take long.

**Comment by geolocus** [comment]
Does it launch without SOAP WSDL on local machine? or WSDL is actual mandatory here?
