### ISSUE TITLE
Dependency test runs great but not Ifcconverter.

### ISSUE THREAD

**Issue by geolocus** [Erfan-Shooraj/ifc2b3dm#7]
Dependency test runs great but not Ifcconverter. Maven script creates project in Bimserver. 

Ifc converter Main.java still cannot reach Bimclient:
Error: Unable to initialize main class ifcconverter.Main
Caused by: java.lang.NoClassDefFoundError: BimServerClient

Maven dependencys pom files on both accurately the same.

Bimserver 1.5.147

JDK12

Eclipse Modeling Tools

Version: 2019-03 (4.11.0)
Build id: 20190314-1200

**Comment by Erfan-Shooraj** [comment]
I think it's because you need to use JDK8

https://github.com/opensourceBIM/BIMserver/wiki/Requirements-1.5

**Comment by geolocus** [comment]
I think its either problem with JDK and Eclipse, Eclipse and Bimserver or JDK and Bimserver. Which setup of versions runs on your machine? 




Gauti „Outlook“, skirtą „Android“







On Thu, Jun 6, 2019 at 7:13 AM +0200, "Erfan-Shooraj" <notifications@github.com> wrote:












I think it's because you need to use JDK8


https://github.com/opensourceBIM/BIMserver/wiki/Requirements-1.5

**Comment by Erfan-Shooraj** [comment]
You should set the JRE in eclipse to 1.8. That's the version I'm using and I can connect to BimServer running locally.

Also, if you change the version in pom file make sure it's the exact same as the one in your BimServerClientLib pom file with the ending SNAPSHOT if there is one.

**Comment by geolocus** [comment]
Your eclipse is latest release? 




Gauti „Outlook“, skirtą „Android“







On Thu, Jun 6, 2019 at 12:45 PM +0200, "Erfan-Shooraj" <notifications@github.com> wrote:












You should set the JRE in eclipse to 1.8. That's the version I'm using and I can connect to BimServer running locally.


Also, if you change the version in pom file make sure it's the exact same as the one in your BimServerClientLib pom file with the ending SNAPSHOT if there is one.

**Comment by Erfan-Shooraj** [comment]
No but eclipse version shouldn't be your problem. You can try running the project as maven build. even if the build fails it can resolve the dependencies from pom file

**Comment by geolocus** [comment]
Ifc2b3dm as Maven? 




Gauti „Outlook“, skirtą „Android“







On Thu, Jun 6, 2019 at 2:17 PM +0200, "Erfan-Shooraj" <notifications@github.com> wrote:












No but eclipse version shouldn't be your problem. You can try running the project as maven build. even if the build fails it can resolve the dependencies from pom file

**Comment by Erfan-Shooraj** [comment]
yes

**Comment by geolocus** [comment]
262182
java.io.FileNotFoundException: C:\bin\IfcOpenShell-masterlabamba\labamba.json (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at ifcconverter.Main.main(Main.java:82)

everything worked what you have mentioned, but now Im here.

**Comment by Erfan-Shooraj** [comment]
Seems like you don't have the json file of your project in your converter folder. Just download your model as json and put it in the converter folder. It should solve the error.

You can also uncomment the downprojectjson line on line 63 but sometimes it doesn't work
